[package]
name = "deploy"
version = "0.1.0"
authors = ["notgne2 <gen2@gen2.space>", "Serokell <hi@serokell.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.2", features = ["wrap_help", "derive"] }
flexi_logger = { version = "0.23.3", features = ["use_chrono_for_offset"] }
fork = "0.1"
futures-util = "0.3.24"
log = "0.4"
merge = "0.1.0"
notify = "5.0.0"
rnix = "0.10.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
signal-hook = "0.3"
thiserror = "1.0"
tokio = { version = "1.21.2", features = [
        "process",
        "macros",
        "sync",
        "rt-multi-thread",
        "fs",
        "time",
] }
toml = "0.5"
whoami = "1.2.3"
yn = "0.1"
